# Generated by Django 4.1.5 on 2023-01-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('pH', models.FloatField(verbose_name='pH')),
                ('turbidity', models.FloatField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('z_position', models.FloatField()),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='probe.probe')),
            ],
        ),
    ]
